// react-js/src/components/LearnMode.js
import React from 'react';
import './LearnMode.css';

class LearnMode extends React.Component {
  render() {
    return (
      <div className="LearnMode">
        <h1>{this.props.terms[0].word}</h1>
        <form>
          <input className="LearnMode-input" type="text" />
          <button className="LearnMode-submit" type="submit">
            Submit
          </button>
        </form>
      </div>
    );
  }
}

export default LearnMode;

// angular/angular8/src/app/learn-mode/learn-mode.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: "app-learn-mode",
  templateUrl: "./learn-mode.component.html",
  styleUrls: ["./learn-mode.component.css"]
})
export class LearnModeComponent implements OnInit {

   terms = [
    {
      id: 1,
      word: "Nebraska",
      definition: "Lincoln"
    },
    {
      id: 2,
      word: "Massachusetts",
      definition: "Boston"
    },
    {
      id: 3,
      word: "California",
      definition: "Sacramento"
    }
  ];

  constructor() {}

  ngOnInit() {}

}

<main id="root">
  <div class="LearnMode">
    <h1 class="LearnMode-prompt">{{terms[0].word}}</h1>
    <form class="LearnMode-form">
      <input autofocus class="LearnMode-input" type="text" />
      <button class="LearnMode-submit" type="submit">Submit</button>
    </form>
  </div>
</main>
