// vue-js/src/App.vue
<template>
  <LearnMode :terms="terms" />
</template>

<script>
import LearnMode from './components/LearnMode.vue'

export default {
  name: 'app',
  components: {
    LearnMode
  },
  setup() {
    return {
      terms: [
        {
          id: 1,
          word: 'Nebraska',
          definition: 'Lincoln',
        },
        {
          id: 2,
          word: 'Massachusetts',
          definition: 'Boston',
        },
        {
          id: 3,
          word: 'California',
          definition: 'Sacramento',
        },
      ]
    };
  }
}
</script>

<style>
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  margin: 0;
  padding: 0;
}
</style>

// react-js/src/App.js
import React from 'react'
import './App.css'
import LearnMode from './components/LearnMode'

const TERMS = [
  {
    id: 1,
    word: 'Nebraska',
    definition: 'Lincoln',
  },
  {
    id: 2,
    word: 'Massachusetts',
    definition: 'Boston',
  },
  {
    id: 3,
    word: 'California',
    definition: 'San Francisco',
  }
]

class App extends React.Component {

  render = () => {
    return (
      <LearnMode terms={TERMS} />
    )
  }
}

export default App
